### ISSUE TITLE
Request to add preview of ui in the Readme section

### ISSUE THREAD

**Issue by SyedNekoChan** [Kezyma/UI-Remastered#1]
Hello there. I am not sure if you are still active on the project but I would really love to request a preview of the remastered ui in the readme section. Anything from image to gif would look nice as it would show viewers what to expect before getting the files.

**Comment by Kezyma** [comment]
The readme on here is obsolete as this isn't really the appropriate place to get a copy of the mod from!
There's the latest documentation and screenshots on the docs website: https://kezyma.github.io/?p=uiremastered
The download, and more of the screenshots are also on NexusMods: https://www.nexusmods.com/morrowind/mods/48987

I'll just point the readme to the documentation site.

**Comment by SyedNekoChan** [comment]
Alright thank you, much appreciated
